---
title: "06_analysis_02.qmd"
format: html
editor: visual
author: "Anna Boateng: s175562, Marlies Goedknegt: s220675, Anne Gjelstrup: s194530, Katja Jagd: s185395, Olivia Ronnenberg: s183359"
---

## Part 06: analysis 2

### Install the required packages

```{r}
#| label: load packages
library("tidyverse")
```

### Plot of target molecules before and after

```{r}
coexpression_aug <- read_tsv("../data/03_coexpression_aug.tsv.gz",
                               show_col_types = FALSE)
```

```{r}
target_aug |> 
  ggplot(aes(x = upstream_regulator,
               y = change_in_n_molecules,
             fill = change_class)) +
  geom_col(color  = "black") + 
   theme_minimal(base_size = 10) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 55,
                                   hjust = 1,
                                   vjust = 1.1)) +
   scale_fill_manual(values = c("#661100","#117733","black")) +
  geom_hline(yintercept = 0) +
  theme(plot.margin = unit(
    c(1, 0.5, 0.5, 1), "cm"),
    panel.grid.major.x = element_blank()) +
  labs(x = "Upstream regulator",
       y = "Change in target molecules",
       title = "Change in target molecules after tDMARD treatment compared to before")
```

```{r}
coexpression_aug 
```

### Header for Anne

```{r}
target_aug <- read_tsv("../data/03_target_aug.tsv.gz",
                       show_col_types = FALSE)
```

```{r}
module_counter <- function(data, ID) {
  data <- data |> 
    filter(upstream_regulator == ID) |>
    select(contains("molecule_before")) |>
    map_df( ~ coexpression_clean |> 
              filter(gene == .x) |>
              select(c("modules",
                       gene))) |>
    count(modules, name = ID)
  
  return (data)
}
```


```{r}
candidate_1 <- module_counter(target_aug, "TREM1")
candidate_2 <- module_counter(target_aug, "LIPE")
candidate_3 <- module_counter(target_aug, "JUND")
```

```{r}
module_analysis <- candidate_1 |> 
  full_join(candidate_2,
            by = 'modules') |> 
  full_join(candidate_3,
            by = 'modules') |> 
  mutate_if(is.numeric,
            replace_na,
            0) |> 
  pivot_longer(cols = -modules,
               names_to = "candidate",
               values_to = "counts") |> 
  arrange(as.integer(str_extract(modules, "\\d+")))
```


```{r}
module_analysis |>
  ggplot(aes(x = modules, y = counts, fill = candidate)) +
  geom_bar(stat = "identity",
           color = "black",
           alpha = 0.4,
           position = position_dodge(preserve = "single")) +
  geom_hline(yintercept = 0) + 
  
  theme(legend.position = "bottom",
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(angle = 20,
                                   hjust = 1,
                                   vjust = 1))
```

