---
title: "07_analysis_3"
format: html
editor: visual
author: "Anna Boateng: s175562, Marlies Goedknegt: s220675, Anne Gjelstrup: s194530, Katja Jagd: s185395, Olivia Ronnenberg: s183359"
---
### Import required packages

```{r}
#| label: load packages
#| message: false
library("ggrepel")
library("tidyverse")
```

```{r}
expr_data_before_unfiltered_aug <- read_tsv("../data/03_expr_data_before_unfiltered_aug.tsv.gz",
                               show_col_types = FALSE)

expr_data_after_unfiltered_aug <- read_tsv("../data/03_expr_data_after_unfiltered_aug.tsv.gz",
                               show_col_types = FALSE)
```

```{r}

expr_data_before_unfiltered_aug <- expr_data_before_unfiltered_aug |>
  mutate(lbl = case_when(is_significant == "yes" ~ upstream_regulator,
                         is_significant == "no" ~ ""))

expr_data_before_unfiltered_aug |>
  ggplot(aes(x = expr_log_ratio_before,
             y = log10_p_value_before,
             colour = is_significant,
            label = lbl)) + 
  geom_text_repel(size = 3,
                  max.overlaps = 25) + 
  geom_point() +
  xlim(-5, 5) + 
  geom_hline(yintercept = -log10(0.05), linetype = "dotted", color = "black") + 
  geom_vline(xintercept = c(-1.5, 1.5), linetype = "dotted", color = "black") 
  
```

```{r}

expr_data_after_unfiltered_aug <- expr_data_after_unfiltered_aug |>
  mutate(lbl = case_when(is_significant == "yes" ~ upstream_regulator,
                         is_significant == "no" ~ ""))

expr_data_after_unfiltered_aug |>
  ggplot(aes(x = expr_log_ratio_after,
             y = log10_p_value_after,
             colour = is_significant,
            label = lbl)) + 
  geom_text_repel(size = 3,
                  max.overlaps = 25) + 
  geom_point() +
  xlim(-5, 5) + 
  geom_hline(yintercept = -log10(0.05), linetype = "dotted", color = "black") + 
  geom_vline(xintercept = c(-1.5, 1.5), linetype = "dotted", color = "black") 
  
```


```{r}
expr_analysis <- read_tsv("../data/03_expr_aug.tsv.gz",
                      show_col_types = FALSE)

```

```{r}
expr_analysis <- expr_aug |> 
  select(contains("regula"), contains("change"))
  
```

```{r}
expr_analysis |> 
  ggplot(aes(x = change_in_expr,
             y = upstream_regulator,
             color = regulation)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dotted", color = "black") 
           
```

